* Scarabeus

  Issure tracking service.

** Versions

*** Basic (FE only)
    Data stored locally in localStorage. No collaboration, no authentication.

*** Middle
    Option to change users, authorization. Still all in FE.

*** Complete
    Data stored in DB, auth in BE.

** FE Stack
   - Javascript
   - Bootstrap
   - React
   - Jest (tests)
   - Cypress (E2E tests)

** Plan

   With the intent to become an FE developer in 6 months most time should be
   spent on the Basic version. If for some reason we are too efficient we can
   try working on the other parts as well.

   Basic version features we want to implement:
   - add an issue (issue has title, comment, tags, solver, open/closed state)
   - edit existing issue
     - change title
     - change comment
     - add tags
     - change tags
     - delete tags
     - add solver
     - change solver
     - delete solver
     - close issue
     - reopen issue
   - delete issue (maybe?)
   - add comment to issue
   - edit comment
   - react to comment (thumbs-up, heart etc emojis)
   - delete comment (maybe?)
   - show issue list
   - filter issue list by solver/title/tags/state
   - export issue list to JSON
   - save issues to LocalStorage
   - load issues from LocalStorage
   - create user
   - edit user profile
     - change display name
     - change avatar
   - delete user
   - switch to different user

*** TODO Initialize an empty React project

    Use [[https://create-react-app.dev/][create-react-app]] to initialize an empty React project. Make sure you are
    able to start a live-reloading web server. Use =npm=, not =yarn=.

*** TODO First commit                                                   :Git:
    Commit your app wih a meaningful commit. From here on no new steps for
    commits will be present, it is implicitly expected you commit each step
    separately.

*** TODO Install Cypress locally (through npm)
    Use the [[https://docs.cypress.io/guides/getting-started/installing-cypress#Switching-browsers][local installation through npm]].

*** TODO First test                                                 :Cypress:
    Test that a button with text "New issue" and an id "sb-new-issue-button" is
    present on the page.

*** TODO First React                                                  :React:
    Implement the first test. Don't write more code than necesary to pass the
    test. Use React to mount the button upon page initialization.

*** TODO Styling test                                                  :Jest:
    Test that the "New Issue" button has a "btn-primary" bootstrap class. Use
    Jest for unit (component) testing this time.

*** TODO First CSS                                                :Bootstrap:
    Implement the previous test. Don't write more code than necessary to pass
    the test.

*** TODO First interaction test                                     :Cypress:
    Test that clicking the "New Issue" button shows a new form with id
    "new-issue-form".

*** TODO First React interaction                                      :React:
    Implement the previous test. Don't write more code than necessary to pass
    the test.
